### ISSUE TITLE
Update the version constant when release

### ISSUE THREAD

**Issue by shouichi** [zengin-code/zengin-rb#2]
Hi,

Could you update the ZenginCode version constant when releasing a new version? We want to cache the data from this gem and want to use the version as a part of cache keys. We use `Gem.loaded_specs["zengin_code"].version.to_s` to get the gem version but just `ZenginCode.version` would be much nicer.

Thank you.

**Comment by rosylilly** [comment]
@shouichi Already included `updated_at` in `ZenginCode.version`. You can use that for a cache key.

```
> ZenginCode.version
=> "1.0.1-p20201212"
```

**Comment by shouichi** [comment]
Cool, thanks for the tip!
