### ISSUE TITLE
Provide rails integration

### ISSUE THREAD

**Issue by shouichi** [zengin-code/zengin-rb#3]
Hi, do you accept rails integration to this gem or should we create a new gem on top of this one (e.g., `zengin_code-rails`)? Thanks.

**Comment by rosylilly** [comment]
This gem is a simple data set gem. What kind of features are you looking for in Rails Integration?

**Comment by shouichi** [comment]
The feature I was looking for was a rails engine that we can mount in the main rails app and serves API to list banks/branches. We built and published a gem works that way https://github.com/anipos/zengin-code-rails.

Thanks!
